project_id = "iyccgbrarlvsaojzydjq"

[functions.chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.extract-memory]
verify_jwt = false

[functions.study-coach]
verify_jwt = true

[functions.future-predict]
verify_jwt = false

[functions.generate-chat-title]
verify_jwt = false

[functions.leaderboard]
verify_jwt = true

[functions.connect-openai]
verify_jwt = false

[functions.disconnect-openai]
verify_jwt = false

[functions.update-ai-preferences]
verify_jwt = false
