// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-subjects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_subjects_default = defineTool({
  name: "list_subjects",
  title: "List study subjects",
  description: "Return the signed-in user's study subjects with weekly targets.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("study_subjects").select("id, subject_name, color, weekly_target_minutes, priority_order").order("priority_order", { ascending: true, nullsFirst: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { subjects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "List study tasks",
  description: "List the signed-in user's study tasks, optionally filtered by status or date.",
  inputSchema: {
    status: z.enum(["pending", "in_progress", "completed"]).optional().describe("Filter by status."),
    date: z.string().optional().describe("YYYY-MM-DD; filter to this task_date."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("study_tasks").select("id, topic, subject_id, task_date, status, difficulty, duration_minutes, started_at, completed_at").order("task_date", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (date) q = q.eq("task_date", date);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_task_default = defineTool3({
  name: "create_task",
  title: "Create study task",
  description: "Create a new study task on the user's plan.",
  inputSchema: {
    topic: z2.string().trim().min(1).max(200).describe("What to study."),
    subject_id: z2.string().uuid().optional().describe("Related study_subjects.id."),
    task_date: z2.string().optional().describe("YYYY-MM-DD; defaults to today."),
    duration_minutes: z2.number().int().min(5).max(600).optional().describe("Planned duration (default 25)."),
    difficulty: z2.enum(["easy", "medium", "hard"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("study_tasks").insert({
      user_id: ctx.getUserId(),
      topic: input.topic,
      subject_id: input.subject_id ?? null,
      task_date: input.task_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      duration_minutes: input.duration_minutes ?? 25,
      difficulty: input.difficulty ?? "medium",
      status: "pending"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created task ${data.id}: ${data.topic}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/log-session.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var log_session_default = defineTool4({
  name: "log_study_session",
  title: "Log a completed study session",
  description: "Record a completed focus session (minutes spent on a topic).",
  inputSchema: {
    topic: z3.string().trim().min(1).max(200),
    time_spent_minutes: z3.number().int().min(1).max(600),
    subject_id: z3.string().uuid().optional(),
    task_id: z3.string().uuid().optional(),
    accuracy_score: z3.number().min(0).max(100).optional(),
    notes: z3.string().max(1e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("study_sessions").insert({
      user_id: ctx.getUserId(),
      topic: input.topic,
      time_spent_minutes: input.time_spent_minutes,
      subject_id: input.subject_id ?? null,
      task_id: input.task_id ?? null,
      accuracy_score: input.accuracy_score ?? null,
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${data.time_spent_minutes}m on "${data.topic}"` }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/tools/study-stats.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var study_stats_default = defineTool5({
  name: "get_study_stats",
  title: "Get study statistics",
  description: "Total minutes studied and session count over the last N days (default 7), broken down by subject.",
  inputSchema: {
    days: z4.number().int().min(1).max(90).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const window = days ?? 7;
    const since = new Date(Date.now() - window * 864e5).toISOString().slice(0, 10);
    const client = sb5(ctx);
    const [{ data: sessions, error: sErr }, { data: subjects }] = await Promise.all([
      client.from("study_sessions").select("time_spent_minutes, subject_id, topic, session_date").gte("session_date", since),
      client.from("study_subjects").select("id, subject_name")
    ]);
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    const subjectMap = new Map((subjects ?? []).map((s) => [s.id, s.subject_name]));
    const bySubject = {};
    let totalMinutes = 0;
    for (const s of sessions ?? []) {
      totalMinutes += s.time_spent_minutes ?? 0;
      const name = s.subject_id ? subjectMap.get(s.subject_id) ?? "Unassigned" : "Unassigned";
      bySubject[name] = (bySubject[name] ?? 0) + (s.time_spent_minutes ?? 0);
    }
    const summary = {
      window_days: window,
      total_minutes: totalMinutes,
      session_count: sessions?.length ?? 0,
      minutes_by_subject: bySubject
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iyccgbrarlvsaojzydjq";
var mcp_default = defineMcp({
  name: "studytime-mcp",
  title: "StudyTime MCP",
  version: "0.1.0",
  instructions: "Tools for StudyTime: inspect and modify the signed-in user's study plan. Use `list_subjects` to see subjects, `list_tasks` for the plan, `create_task` to add a task, `log_study_session` to record completed focus time, and `get_study_stats` for weekly totals.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_subjects_default, list_tasks_default, create_task_default, log_session_default, study_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
